= Jason N Mansfield 2019 Curriculum Vitae
Jason Mansfield  <trentonknight@gmail.com>
1.0, Jan 17, 2019, Curriculum Vitae
:toc: left
:icons: font
//:source-highlighter: prettify
:source-highlighter: rouge

== Contact Information

[%header,cols=2*]
|===
|Contact method
|

|Telephone
|(757) 753-0085

|Email
|trentonknight@gmail.com

|Social
|https://www.linkedin.com/in/trentonknight/[trentonknight @ *Linkedin*]

|===


== Education
.Universities Attended
* *2005-2006*
** ECPI University
*** 5555 Greenwich Rd. Virginia Beach, VA 23462
*** IT/Computer Programming
* *2007-2013* 
** REGIS University
*** 3333 Regis Boulevard. Denver, CO 80221-1099
*** Bachelor of Science in Computer Science
**** Graduated with 3.413 GPA
**** Deans list Spring of 2013
**** CPS accredited by the Computing Commission of ABET
****
Awarded a Bachelor of Science in Computer Science from Regis University on the 23rd of August 2013 with a GPA of 3.413. The Computing Accreditation Commission of ABET accredits this Computer Science degree. Additionally, after receiving a grade of A in both Calculus I and II, followed by an A in Linear Algebra, I earned Dean List Recognition in the Spring of 2013.
****

== Work History

.Brief on work history
* U.S. Coast Guard Cyber Command
** Timeframe: 2017 to current
*** Position Title: Battle Bridge Supervisor
*** Address: Base National Capital Region. 2701 Martin Luther King Jr Ave SE. Washington, DC 20593
*** Job description
****
As a watch supervisor for the U.S. Coast Guard Cyber Command (CGCYBER), Network Operations and Security Center (NOSC), Enterprise Operations Center (EOC), Battle bridge I am responsible for managing and leading the Analysts in successfully meeting senior leadership expectations of monitoring enterprise information systems for critical events, remedying incidents & problems, granting or denying access requests, and fulfilling valid requests. Additionally, I spend some time training new and existing analysts with developing new Powershell scripts to help with the automation of goals in bulk or faster. Watch Supervisors develop and perform the DODIN and bi-weekly briefs to Leadership directly.
****
* USCGC DILIGENCE WMEC-616
** Timeframe: 2014 to 2017
*** Position Title: Cutter Systems Manager
*** Address: USCGC DILIGENCE (WMEC 616). 109 North Water Street. Wilmington, N.C. 28401
*** Job description
****
While attached to this unit I independently managed the USCGC DILIGENCE shipboard LAN network, this included cabling, and security for two Cisco 3750G switches. Troubleshot shore side cabling issues connecting to WAN infrastructure in multiple locations such as Wilmington, NC, Key West Florida, Naval Station Guantanamo Bay Cuba, Naval Station Mayport Florida. Shipboard administrator for two host servers each containing multiple virtual servers including Microsoft Server 2008 R2 and Microsoft Exchange and others. I Managed both CGONE and SIPR networks and all associated equipment such as TACLANE, Routers, HDSL modems, and all cabling onboard and to the WAN. Administrated, repaired and replaced several satellite systems such as KVH (KU-Band) and Fleet Broadband (Inmarsat B). Maintained all shipboard workstations on both CGONE and SIPR networks handling installing, updating, recap, drmo and secure destruction of all associated hardware. Supported all shipboard printers including CGONE and SIPR side hardware. Maintained shipboard phone systems. Above duties as the only onboard technician, I was expected to qualify and stand watch as a "boatswain mate of the watch," "gangway petty officer of the watch," and "sounding and security watch." I volunteered for and stood security watch for law enforcement operations dealing with illegal migrants and drug trafficking detainees and "Anti Terrorist Force Protection."
****
* ESD CHESAPEAKE/FINCEN INFO SYS DIV
** Timeframe: 2010 to 2014
*** Position Title: Systems Service Technician
*** Address: USCG Finance Center. 1430A Kristina Way. Chesapeake, VA 23326
*** Job description
****
ESD Chesapeake is located at the US Coast Guard Finance Center in Chesapeake Virginia. I performed many tasks related to IT related inventory. I spent almost 75% of my time involved in Custodian associated functions during my first two years at FinCEN. I was assigned the responsibility of TASM or Trusted Agent Security Manager for a period. The TASM duty required me to manage our Trusted Agents and monitor their Certification Training and other needs. The Finance Center has two buildings, one consisting of primary accountants and financial type managers, while the second building annex houses primarily Database Administrators. The DBA's develop and maintain the business application, and we as Information Technology Specialists support Standardized workstations. Due to the vast variety of software used, the need for a solid understanding of Oracle database clients, Java environments, ODBC drivers and other financial suites needed. I also administrated a Nortel/Avaya CS1000 Public Branch Exchange and its associated premise, circuits and designated phones. I was awarded the Commandant’s Letter of Commendation upon my departure from the USCG Finance center.
****
* USCGC LEGARE WMEC-912
** Timeframe: 2007 to 2010
*** Position Title: Cutter Systems Manager
*** Address: USCGC LEGARE (WMEC-616). 4000 Coast Guard Blvd. Portsmouth, VA 23703
*** Job description
****
During my service with the USCGC LEGARE WMEC-912. I was a Surface swimmer, Combat Watchstander, Radio Watchstander, Bearing taker, Anti Terrorism Force Protection and many other responsibilities. Our primary missions were Law Enforcement related. Technician wise I administrated a Windows Exchange server and our Windows based customers as well as maintained an eON PBX and associated cabling. Satellite connectivity was always an issue and required constant adjustments and maintenance. During a 2009 mission to Africa I was appointed to administrate a VMWare based Linux server which hosted our guest nations, this was part of an ongoing effort to improve various African countries maritime security forces. I also installed and administrated our SCCS or Shipboard Command and Control System a UNIX based platform. I received a Letter of Commendation at the end of this tour.

****
* U.S. NAVY STRIKE FIGHTER SQUADRON EIGHT-ONE VFA-81
** Timeframe: 2003 to 2005
*** Position Title: Aviation Ordnanceman (AO) 
*** Address: Naval Air Station Oceana. 1750 Tomcat Blvd. Virginia Beach, VA 23460 
*** Job description
****
In 2004 VFA-81 I deployed with Carrier Air Wing Seventeen CVW-17 on the USS John F. Kennedy CV-67 for its final cruise before decommissioning. My time in the Mediterranean and the Arabian Sea consisting of standard Aviation Ordnanceman tasks such as weapons systems maintenance, loading team member and other flight operation related efforts on the flight deck. During the course of operations in Iraq, 54,000 pounds of ordnance were dropped by the jets of CVW-17 squadrons, including F/A-18s Hornets from the Blue blaster of Strike Fighter Squadron (VFA) 34, the Rampagers of VFA-83, the Sunliners of VFA-81 and F-14 Tomcats from the Jolly Rogers of Fighter Squadron (VF) 103. The John F. Kennedy Strike group supported Operations "Iraqi Freedom," "Enduring Freedom," and "Al Fajr." During flight operations, I spend the majority of my time (arming) and retrieving (de-arming if needed) several jets, something which became critical near the end of this patrol during Al Fajr or the second battle of Fallujah.

****
* U.S. NAVY STRIKE FIGHTER SQUADRON ONE TWO FIVE VFA-125
** Timeframe: 2001 to 2003
*** Position Title: Aviation Ordnanceman (AO)
*** Address: 330 Reeve Blvd. Hangar 5 Mod 1. Naval Air Station Lemoore, CA 93246
*** Job description
****
I spent my first two years in the US Navy at STRIKE FIGHTER SQUADRON ONE TWO FIVE VFA-125 ROUGH RAIDERS directly after boot camp and A school. I learned how to load and lead ordnance loading teams in a professional manner, flight deck operations, ordnance safety and many other basics during this timeframe. I had the pleasure of working with and for US Marines during my time with the Rough Raiders. I was awarded a Letter of Commendation at the end of this tour.
****
== Professional and educational experience
=== Programming Languages
I have the most experience with the following languages.

==== RUST
[source, rust]
----
fn aws_serverless(){
  println!("Currently working to develop a service with AWS Lambda");
}

fn main() {
    println!("RUST language!");
}
----
==== C and C++
[source, cpp]
----
int main() {
  cout << "C and C++";
  cout << "Used throughout college for learning basic algorithms."
}
----
==== Python
[source, python]
----
import pandas as used_for_searching_csv_files
from  scipy import used_for_many_years_scipy_addict
import matplotlib.pyplot as used_for_years
import numpy as same
from sklearn import of_course

print("Python!")
----
==== Powershell  
[source, powershell]
----
import-module activedirectory

$Session = New-PSSession -ConfigurationName Microsoft.Exchange 

write-host "Primarily use Powershell for analyst efforts at CGCYBER."
----

==== LaTeX 
[source, LaTeX]
----
\documentclass{article}
\begin{document}
LaTeX
\end{document}
----

==== Java 

[source, Java]
----
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {

    String java = "Used Android Studio primarily throughout college. Used for senior
    capstone project."
}
----

=== Software Architectures and Engineering experience

----
Openstack, Moodle, Wordpress, Microsoft Active Directory and Exchange, Git hosting, Docker, and custom websites using various open source SQL database. 
----

=== Research

----
My current effort is to create a serverless application using the RUST Language with a container based platform. I am exploring options with various approaches such as AWS Lambda, Kubernetes, and Apache OpenWhisk. Clearly RUST is a new language and for now some efforts may require use of Node.js. Additionally, I am investigating WebAssembly    
----


== How to best view this Resume

This resume has been written for viewing as plain text ascii or may be improved using link:https://asciidoctor.org/[asciidoctor.]

=== Viewing as a PDF

To view as a PDF use the following URL: link:https://github.com/trentonknight/jnmansfield_cvitae/blob/master/jnmansfield_resume2019.pdf[jnmansfield_resume2019.pdf]

=== Viewing as HTML


==== Grab HTML version from GitHub
Clone the latest version of this resume. The latest version of this resume may be retrieved here: 
----
git clone https://github.com/trentonknight/jnmansfield_cvitae.git
----
Using a browser
----
firefox jnmansfield_cvitae/jnmansfield_resume2019.html &
----

==== Install asciidoctor for compiling and using resume as a template.
The asciidoctor tool must be installed to compile. Examples are below or more may be
found on *Github* here: link:https://github.com/asciidoctor/asciidoctor[asciidoctor @ *GitHub*]

Arch Linux
----
pacman -S asciidoctor
----

Fedora Linux
----
dnf -y install asciidoctor
----

Ruby Install
----
gem install asciidoctor
----

Install from source code
----
git clone https://github.com/asciidoctor/asciidoctor.git
----
TIP: asciidoctor files need to be saved with the extension *.adoc. 

==== If needed change the file format extension to *.adoc.
----
mv jnmansfield_resume2019.txt my_new_resume.adoc
----

==== Use link:https://github.com/asciidoctor/asciidoctor[asciidoctor] to export HTML or PDF

===== HTML creation
----
asciidoctor my_new_resume.adoc
----
===== PDF creations using link:https://asciidoctor.org/docs/asciidoctor-pdf/[asciidoctor-pdf]
----
asciidoctor-pdf my_new_resume.adoc
----
===== Add CSS using link:https://github.com/asciidoctor/asciidoctor-stylesheet-factory[asciidoctor-stylesheet-factory]
----
asciidoctor -a stylesheet=gonavy.css my_new_resume.adoc
----



